I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/ctg_MiniGame.rpy", line 35, in script call
    call show_room from _call_show_room
  File "game/scripts/ctg_MiniGame.rpy", line 47, in script call
    call screen display_items(room_name)
  File "game/scripts/ctg_MiniGame.rpy", line 47, in script call
    call screen display_items(room_name)
  File "game/scripts/ctg_MiniGame.rpy", line 47, in script call
    call screen display_items(room_name)
  [Previous line repeated 7 more times]
  File "game/script.rpy", line 1477, in script
    strnager "The Shadow would’ve taken her, just like all the others."
Exception: Sayer 'strnager' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/ctg_MiniGame.rpy", line 35, in script call
    call show_room from _call_show_room
  File "game/scripts/ctg_MiniGame.rpy", line 47, in script call
    call screen display_items(room_name)
  File "game/scripts/ctg_MiniGame.rpy", line 47, in script call
    call screen display_items(room_name)
  File "game/scripts/ctg_MiniGame.rpy", line 47, in script call
    call screen display_items(room_name)
  [Previous line repeated 7 more times]
  File "game/script.rpy", line 1477, in script
    strnager "The Shadow would’ve taken her, just like all the others."
  File "C:\Users\artra\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\artra\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\artra\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'strnager' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
A long way home 0.9
Sun Dec 29 20:26:07 2024
